apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: product-circuit-breaker
  namespace: istio-demo
spec:
  host: product
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3s
      maxEjectionPercent: 100
      minHealthPercent: 0
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: slow-service-circuit-breaker
  namespace: istio-demo
spec:
  host: slow-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 5
      http:
        http1MaxPendingRequests: 5
        maxRequestsPerConnection: 5
        http2MaxRequests: 10
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
